/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sponsors: Sponsor;
    groups: Group;
    people: Person;
    applicants: Applicant;
    awards: Award;
    awardees: Awardee;
    tdks: Tdk;
    faqs: Faq;
    reports: Report;
    'apply-timeline-event': ApplyTimelineEvent;
    'about-timeline-event': AboutTimelineEvent;
    events: Event;
    'community-pictures': CommunityPicture;
    'course-categories': CourseCategory;
    courses: Course;
    odyssey: Odyssey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    applicants: ApplicantsSelect<false> | ApplicantsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    awardees: AwardeesSelect<false> | AwardeesSelect<true>;
    tdks: TdksSelect<false> | TdksSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'apply-timeline-event': ApplyTimelineEventSelect<false> | ApplyTimelineEventSelect<true>;
    'about-timeline-event': AboutTimelineEventSelect<false> | AboutTimelineEventSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'community-pictures': CommunityPicturesSelect<false> | CommunityPicturesSelect<true>;
    'course-categories': CourseCategoriesSelect<false> | CourseCategoriesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    odyssey: OdysseySelect<false> | OdysseySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Felhasználók, akik be tudnak jelentkezni az admin felületre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Szponzorok, akik támogatják a szakkollégiumot.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  members?:
    | {
        member: number | Person;
        role?: string | null;
        joined_at?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  picture?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicants".
 */
export interface Applicant {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  name: string;
  logo: number | Media;
  about: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  awardees?: (number | Awardee)[] | null;
  covers?:
    | {
        cover: number | Media;
        id?: string | null;
      }[]
    | null;
  facebook_link?: string | null;
  event_facebook_link?: string | null;
  connected_publicatios?: number | null;
  block_seminar_participants?: number | null;
  lecture_participants?: number | null;
  video?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awardees".
 */
export interface Awardee {
  id: number;
  name: string;
  institution: string;
  origin_country: string;
  fields_of_science: {
    field: string;
    id?: string | null;
  }[];
  fields_of_science_en: {
    field: string;
    id?: string | null;
  }[];
  about: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  about_en: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  short_justification: string;
  short_justification_en: string;
  extended_justification?: string | null;
  extended_justification_en?: string | null;
  year: number;
  picture: number | Media;
  has_nobel?: boolean | null;
  nobel_year?: number | null;
  ceremony_video_link?: string | null;
  lecture_video_link?: string | null;
  image_gallery: {
    image: number | Media;
    caption: string;
    caption_en: string;
    id?: string | null;
  }[];
  related_content: {
    title: string;
    title_en: string;
    url: string;
    thumbnail?: (number | null) | Media;
    type: 'article' | 'interview' | 'video' | 'other';
    id?: string | null;
  }[];
  downloads: AwardeeDownloads;
  publications: {
    title: string;
    title_en: string;
    author: string;
    date: string;
    link?: string | null;
    id?: string | null;
  }[];
  websites: AwardeeWebsites;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardeeDownloads".
 */
export interface AwardeeDownloads {
  laudation_pdf?: (number | null) | Media;
  press_photo_pack?: (number | null) | Media;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardeeWebsites".
 */
export interface AwardeeWebsites {
  google_scholar_link?: string | null;
  personal_website_link?: string | null;
  institution_website_link?: string | null;
  nobel_website_link?: string | null;
}
/**
 * TDK dolgozatok
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tdks".
 */
export interface Tdk {
  id: number;
  title: string;
  section_name?: string | null;
  author?: (number | Person)[] | null;
  year?: number | null;
  placement?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * TDK dolgozatok
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Jelentések
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  title: string;
  topic: string;
  link: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply-timeline-event".
 */
export interface ApplyTimelineEvent {
  id: number;
  name: string;
  date: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-timeline-event".
 */
export interface AboutTimelineEvent {
  id: number;
  name: string;
  date: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Események és eseményekkel kapcsolatos információk
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  picture: number | Media;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  date: string;
  location: string;
  speakers?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Közösségi események képei
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-pictures".
 */
export interface CommunityPicture {
  id: number;
  name: string;
  picture: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-categories".
 */
export interface CourseCategory {
  /**
   * The display name of the category
   */
  name: string;
  /**
   * Unique identifier for the category (e.g., "arts", "science")
   */
  id: string;
  /**
   * A color code for the category, e.g. "#ff5733"
   */
  color: string;
  /**
   * A brief description of this course category
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * The name of the course
   */
  title: string;
  /**
   * A brief description of the course
   */
  description?: string | null;
  /**
   * Link to the course details
   */
  link?: string | null;
  /**
   * Icon to represent the course
   */
  icon:
    | 'BookOpen'
    | 'Calculator'
    | 'Globe'
    | 'Palette'
    | 'Code'
    | 'Users'
    | 'TrendingUp'
    | 'Lightbulb'
    | 'Target'
    | 'Database'
    | 'Settings'
    | 'Puzzle'
    | 'Monitor'
    | 'FileText'
    | 'Search'
    | 'BarChart'
    | 'Download'
    | 'MessageCircle'
    | 'PenTool'
    | 'Layers';
  /**
   * Position on the course map
   */
  position: {
    /**
     * Top position (e.g., "50%")
     */
    top: string;
    /**
     * Left position (e.g., "50%")
     */
    left: string;
  };
  /**
   * The category this course belongs to
   */
  category: string | CourseCategory;
  /**
   * Controls the order in which courses appear (lower numbers appear first)
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Jelentések
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "odyssey".
 */
export interface Odyssey {
  id: number;
  participants?:
    | {
        participant: number | Person;
        id?: string | null;
      }[]
    | null;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'applicants';
        value: number | Applicant;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'awardees';
        value: number | Awardee;
      } | null)
    | ({
        relationTo: 'tdks';
        value: number | Tdk;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'apply-timeline-event';
        value: number | ApplyTimelineEvent;
      } | null)
    | ({
        relationTo: 'about-timeline-event';
        value: number | AboutTimelineEvent;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'community-pictures';
        value: number | CommunityPicture;
      } | null)
    | ({
        relationTo: 'course-categories';
        value: string | CourseCategory;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'odyssey';
        value: number | Odyssey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  members?:
    | T
    | {
        member?: T;
        role?: T;
        joined_at?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicants_select".
 */
export interface ApplicantsSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  about?: T;
  awardees?: T;
  covers?:
    | T
    | {
        cover?: T;
        id?: T;
      };
  facebook_link?: T;
  event_facebook_link?: T;
  connected_publicatios?: T;
  block_seminar_participants?: T;
  lecture_participants?: T;
  video?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awardees_select".
 */
export interface AwardeesSelect<T extends boolean = true> {
  name?: T;
  institution?: T;
  origin_country?: T;
  fields_of_science?:
    | T
    | {
        field?: T;
        id?: T;
      };
  fields_of_science_en?:
    | T
    | {
        field?: T;
        id?: T;
      };
  about?: T;
  about_en?: T;
  short_justification?: T;
  short_justification_en?: T;
  extended_justification?: T;
  extended_justification_en?: T;
  year?: T;
  picture?: T;
  has_nobel?: T;
  nobel_year?: T;
  ceremony_video_link?: T;
  lecture_video_link?: T;
  image_gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        caption_en?: T;
        id?: T;
      };
  related_content?:
    | T
    | {
        title?: T;
        title_en?: T;
        url?: T;
        thumbnail?: T;
        type?: T;
        id?: T;
      };
  downloads?: T | AwardeeDownloadsSelect<T>;
  publications?:
    | T
    | {
        title?: T;
        title_en?: T;
        author?: T;
        date?: T;
        link?: T;
        id?: T;
      };
  websites?: T | AwardeeWebsitesSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardeeDownloads_select".
 */
export interface AwardeeDownloadsSelect<T extends boolean = true> {
  laudation_pdf?: T;
  press_photo_pack?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardeeWebsites_select".
 */
export interface AwardeeWebsitesSelect<T extends boolean = true> {
  google_scholar_link?: T;
  personal_website_link?: T;
  institution_website_link?: T;
  nobel_website_link?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tdks_select".
 */
export interface TdksSelect<T extends boolean = true> {
  title?: T;
  section_name?: T;
  author?: T;
  year?: T;
  placement?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  topic?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apply-timeline-event_select".
 */
export interface ApplyTimelineEventSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-timeline-event_select".
 */
export interface AboutTimelineEventSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  description?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  description?: T;
  date?: T;
  location?: T;
  speakers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-pictures_select".
 */
export interface CommunityPicturesSelect<T extends boolean = true> {
  name?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-categories_select".
 */
export interface CourseCategoriesSelect<T extends boolean = true> {
  name?: T;
  id?: T;
  color?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  link?: T;
  icon?: T;
  position?:
    | T
    | {
        top?: T;
        left?: T;
      };
  category?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "odyssey_select".
 */
export interface OdysseySelect<T extends boolean = true> {
  participants?:
    | T
    | {
        participant?: T;
        id?: T;
      };
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}